version: "3.9"

services:
  db:
    image: postgres
    volumes:
      - "./data/db:/var/lib/postgresql/data"
    env_file:
      - .env
    ports: 
      - "5432:5432"

  web:
    image: django_image
    build: .
    command: >
      bash -c "python manage.py migrate
      && python manage.py collectstatic --noinput
      && python manage.py runserver"
    env_file: 
      - .env
    volumes:
      - ./core:/code
    ports:
      - "8000:8000"
    depends_on:
      - db