# Generated by Django 3.2.9 on 2021-11-23 20:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_image', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='images',
            new_name='portfolio',
        ),
        migrations.AddField(
            model_name='image',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
