# Generated by Django 3.2.9 on 2021-11-23 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_image', '0002_auto_20211123_2047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='author',
        ),
        migrations.AddField(
            model_name='comment',
            name='author_name',
            field=models.CharField(default='anonim', max_length=100),
        ),
        migrations.AddField(
            model_name='comment',
            name='text',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AlterField(
            model_name='image',
            name='portfolio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='portfolio_image.portfolio'),
        ),
    ]
